services:
  clay-backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    links:
      - "mongodb"
    volumes:
      - ./backend:/clay-backend
      - /clay-backend/node_modules
    command: npm run docker:compose
  clay-frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/clay-frontend
      - /clay-frontend/node_modules
    command: npm run docker:compose
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/mongodb

volumes:
  db_data:
